image: docker:20.10


before_script:
  - 'which ssh-agent || ( apk add --update --no-cache git openssh-client )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

stages:
  - lint
  - test
  - build
  - deploy

lint:
  stage: lint
  image:
    name: docker/compose:1.27.3
  script:
    - docker-compose build
    - docker-compose run server flake8 --version
    - docker-compose run server flake8 --config=./linters/.flake8 --statistics
  after_script:
    - docker-compose down
  only:
    - merge_request

test:
  stage: test
  image:
    name: docker/compose:1.27.3
  script:
    - docker-compose build
    - docker-compose run --rm server python manage.py test --verbosity 2
  after_script:
    - docker-compose down
  only:
    - merge_request

build-server:
  stage: build
  when: manual
  script:
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/server:$CI_COMMIT_REF_SLUG-latest" . -f ./server/Dockerfile.prod
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/server:$CI_COMMIT_REF_SLUG-latest"
  after_script:
    - docker image rm "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/server:$CI_COMMIT_REF_SLUG-latest"
  only:
    - develop
    - master

build-nginx:
  stage: build
  when: manual
  script:
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/nginx:$CI_COMMIT_REF_SLUG-latest" . -f ./nginx/Dockerfile
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/nginx:$CI_COMMIT_REF_SLUG-latest"
  after_script:
    - docker image rm "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/nginx:$CI_COMMIT_REF_SLUG-latest"
  only:
    - develop
    - master

deploy-develop:
  stage: deploy
  when: manual
  before_script:
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - echo "$DEVELOP_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod +x ./deploy/deploy_develop.sh
  script:
    - ./deploy/deploy_develop.sh $DEVELOP_USER $DEVELOP_HOST
  only:
    - develop

deploy-master:
  stage: deploy
  when: manual
  before_script:
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - echo "$MASTER_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod +x ./deploy/deploy_master.sh
  script:
    - ./deploy/deploy_master.sh $PRODUCTION_USER $PRODUCTION_HOST
  only:
    - master
